import pytest
import os

from collections import namedtuple
from ..checksum import ChecksumGenerator

MockDataset = namedtuple('MockDataset', ['files', 'local_files'])


@pytest.fixture
def test_dataset():
    fixtures_dir = os.path.join(os.path.dirname(__file__), 'fixtures')
    files = ['test_dataset_file_one.txt', 'test_dataset_file_two.txt']
    return MockDataset(files, [os.path.join(fixtures_dir, f) for f in files])


@pytest.fixture
def test_checksum_dict():
    """ sha256 sums for files generated by the sha256sum utility. """
    return {
        'test_dataset_file_one.txt':
            '5e477661749669992878fa91c4a1dda5f42870d9aebdf54fba33070f57a318ef',
            'test_dataset_file_two.txt':
            '30ff85ebcb3eeb4accb992f2c2274b6a67b6f78a23263b6402deeb652a51fc06'
    }


def test_file_checksums(test_dataset, test_checksum_dict):
    checksum_generator = ChecksumGenerator()
    checksum_dict = checksum_generator.file_checksums(test_dataset)
    assert test_checksum_dict == checksum_dict
